controllers/CashTransactionController.php
<?php
namespace app\controllers;

use app\components\Model;
use app\models\form\SendCashForm;
use app\models\form\WithdrawForm;
use Yii;
use app\models\CashTransaction;
use app\models\search\CashTransactionSearch;
use app\components\Controller;
use yii\bootstrap\ActiveForm;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CashTransactionController implements the CRUD actions for CashTransaction model.
 */
class CashTransactionController extends Controller {

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * Lists all CashTransaction models.
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new CashTransactionSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		return $this->render('index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single CashTransaction model.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionView($id) {
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	public function actionSendDownline() {
		$model    = new SendCashForm();
		$data     = new Model();
		$children = $data->getTotalDownline($this->user->id);
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post())) {
			if($model->sendDown()) {
				return $this->redirect(['index']);
			}
		}
		return $this->render('send-downline', [
			'model'    => $model,
			'children' => $children,
		]);
	}

	public function actionSendUpline() {
		$model    = new SendCashForm();
		$data     = new Model();
		$children = $data->getTotalUpline($this->user->id);
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post())) {
			if($model->sendUp()) {
				return $this->redirect(['index']);
			}
		}
		return $this->render('send-upline', [
			'model'    => $model,
			'children' => $children,
		]);
	}

	public function actionWithdraw($type = null) {
		if($type != 1) {
			return $this->render('withdraw-button');
		}
		$model = new WithdrawForm;
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			$transaction          = new CashTransaction();
			$transaction->user_id = $this->user->id;
			$transaction->type    = $transaction::TYPE_WIT;
			$transaction->money   = $model->money;
			$transaction->status  = $transaction::STATUS_PENDING;
			$transaction->date    = date('Y-m-d H:i:s');
			if($transaction->save()) {
				$this->user->accounts->updateAttributes(['cash_account' => $this->user->accounts->cash_account - $model->money]);
			};
			$this->redirect(['index']);
		}
		return $this->render('withdraw', ['model' => $model]);
	}

	/**
	 * Deletes an existing CashTransaction model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionDelete($id) {
		$this->findModel($id)->delete();
		return $this->redirect(['index']);
	}

	/**
	 * Finds the CashTransaction model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 *
	 * @return CashTransaction the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if(($model = CashTransaction::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

views/cash-transaction/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cash-transaction-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'type')->textInput() ?>

    <?= $form->field($model, 'money')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cash-transaction/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CashTransactionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cash-transaction-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'money') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cash-transaction/_send.php
<?php
use app\models\User;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\form\SendCashForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="send-cash-form">
	<?php $form = ActiveForm::begin([
		'layout'               => 'horizontal',
		'enableAjaxValidation' => true,
	]); ?>
	<?= $form->field($model, 'user_id')->widget(Select2::className(), [
		'data' => ArrayHelper::map(User::find()->where([
			'IN',
			'id',
			$children,
		])->all(), 'id', 'username'),
	]) ?>
	<?= $form->field($model, 't_password')->passwordInput() ?>
	<?= $form->field($model, 'money')->textInput() ?>
	<div class="col-sm-offset-3">
		<?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>
</div>

views/cash-transaction/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */

$this->title = 'Create Cash Transaction';
$this->params['breadcrumbs'][] = ['label' => 'Cash Transactions', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cash-transaction-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cash-transaction/index.php
<?php
use app\models\CashTransaction;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CashTransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title                   = 'Cash History';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cash-transaction-index">

	<div class="panel panel-success">
		<div class="panel-heading">MY cash account</div>
		<div class="panel-body">
			<p>Cash account: € <?= number_format($searchModel->user->accounts->cash_account) ?></p>
		</div>
	</div>
	<h1><?= Html::encode($this->title) ?></h1>
	<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

	<p>
	</p>
	<?php
	echo Html::a('Send cash to upline', ['/cash-transaction/send-upline'], ['class' => 'btn btn-warning']);
	echo Html::a('Send cash to downline', ['/cash-transaction/send-downline'], ['class' => 'btn btn-success']);
	echo Html::a('Request Withdrawal', ['/cash-transaction/withdraw'], ['class' => 'btn btn-danger'])
	?>
	<div class="table-responsive">
		<?= GridView::widget([
			'dataProvider' => $dataProvider,
			'filterModel'  => $searchModel,
			//		'tableOptions' => ['class' => 'table-responsive'],
			'columns'      => [
				['class' => 'yii\grid\SerialColumn'],
				[
					'attribute' => 'type',
					'value'     => function (CashTransaction $data) {
						return $data::TYPE[$data->type];
					},
					'filter'    => $searchModel::TYPE,
				],
				[
					'attribute' => 'user_id',
					'value'     => function (CashTransaction $data) {
						return $data->user_id != null ? $data->users->username : null;
					},
					'filter'    => false,
				],
				[
					'attribute' => 'receive_id',
					'value'     => function (CashTransaction $data) {
						return $data->receive_id != null ? $data->receiver->username : null;
					},
					'filter'    => false,
				],
				[
					'attribute' => 'money',
					'value'     => function (CashTransaction $data) {
						return $data->money;
					},
				],
				[
					'attribute' => 'status',
					'value'     => function (CashTransaction $data) {
						return $data::STATUS[$data->status];
					},
					'filter'    => $searchModel::STATUS,
				],
				'date'
				// 'date',
				//			['class' => 'yii\grid\ActionColumn'],
			],
		]); ?>
	</div>
</div>

views/cash-transaction/send-downline.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */
$this->title                   = 'Send cash to downline';
$this->params['breadcrumbs'][] = [
	'label' => 'Send downline',
	'url'   => ['send-downline'],
];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cash-transaction-create">

	<h1><?= Html::encode($this->title) ?></h1>

	<?= $this->render('_send', [
		'model'    => $model,
		'children' => $children,
	]) ?>

</div>

views/cash-transaction/send-upline.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */
$this->title                   = 'Send cash to upline';
$this->params['breadcrumbs'][] = [
	'label' => 'Send upline',
	'url'   => ['send-upline'],
];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cash-transaction-create">

	<h1><?= Html::encode($this->title) ?></h1>

	<?= $this->render('_send', [
		'model'    => $model,
		'children' => $children,
	]) ?>

</div>

views/cash-transaction/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */

$this->title = 'Update Cash Transaction: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cash Transactions', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cash-transaction-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cash-transaction/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CashTransaction */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cash Transactions', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cash-transaction-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'type',
            'money',
            'status',
            'date',
        ],
    ]) ?>

</div>

views/cash-transaction/withdraw-button.php
<?php
/**
 * Created by PhpStorm.
 * User: Yamon-PC
 * Date: 31-May-17
 * Time: 4:18 PM
 */
use yii\helpers\Url;

?>
<?= \yii\bootstrap\Html::a('Bitcoin withdrawal', \yii\helpers\Url::to([
	'cash-transaction/withdraw',
	'type' => 1,
]), ['class' => 'btn btn-warning']) ?>
<?= \yii\bootstrap\Html::a('Bank withdrawal', '#', ['class' => 'btn btn-success']) ?>
<?= \yii\bootstrap\Html::a('Perfect money withdrawal', '#', ['class' => 'btn btn-info']) ?>

views/cash-transaction/withdraw.php
<?php
use app\models\User;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\form\SendCashForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="send-cash-form">
	<?php $form = ActiveForm::begin([
		'layout'               => 'horizontal',
		'enableAjaxValidation' => true,
	]); ?>
	<?= $form->field($model, 't_password')->passwordInput() ?>
	<?= $form->field($model, 'money')->textInput() ?>
	<div class="col-sm-offset-3">
		<?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>
</div>