controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\Controller;
use app\models\form\BuyCoinForm;
use app\models\form\LoginForm;
use app\models\form\ResetForm;
use app\models\form\SellCoinFrom;
use app\models\form\SellTokenForm;
use app\models\form\SignUpForm;
use app\models\form\SupportForm;
use app\models\form\TokenMiningForm;
use app\models\form\TradingMiningForm;
use app\models\LevelCurrent;
use app\models\search\CoinMiningSearch;
use app\models\search\TokenTransactionSearch;
use app\models\StartSetting;
use app\models\Support;
use app\models\TokenTransaction;
use app\models\User;
use app\models\UserKyc;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use yii\helpers\Url;
use yii\web\Response;

class SiteController extends Controller {

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow'   => true,
						'roles'   => ['@'],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionProfile() {
		$model = $this->user;
		if($model->load(Yii::$app->request->post())) {
			if(!$model->save()) {
				echo '<pre>';
				print_r($model->errors);
				die;
			} else {
				return $this->refresh();
			}
		}
		return $this->render('profile', [
			'model' => $model,
			'url'   => Url::to([
				'sign-up',
				'ref' => $this->user->username,
			], true),
		]);
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex() {
		//		echo '<pre>';
		//		print_r(json_decode($country,true));
		//		die;
		if($test = User::findOne(['username' => 'usertest'])) {
			if($test->accounts->cash_account <= 0) {
				$test->accounts->updateAttributes(['cash_account' => 100000]);
			}
		}
		$current_token = StartSetting::find()->orderBy('id DESC')->one();
		$bv_left       = $this->user->currentBonus ? $this->user->currentBonus->current_bv_left : 0;
		$bv_right      = $this->user->currentBonus ? $this->user->currentBonus->current_bv_right : 0;
		$current_bonus = $this->user->currentBonus ? $this->user->currentBonus->total_bonus : 0;
		$user          = $this->user;
		$total_f1      = User::find()->where(['sponsor_id' => $this->user->id])->count();
		$current_level = LevelCurrent::find()->where(['user_id' => $this->user->id])->one();
		$current_level = $current_level ? ($current_level->level ? $current_level->level->name : 'None') : 'None';
		return $this->render('index', [
			'user'          => $user,
			'total_f1'      => $total_f1,
			'bv_left'       => $bv_left,
			'bv_right'      => $bv_right,
			'current_bonus' => $current_bonus,
			'current_level' => $current_level,
			'current_token' => $current_token,
		]);
	}

	public function actionExchange() {
		$token                   = $this->user->accounts->token;
		$coin                    = $this->user->accounts->coin;
		$token_sold              = TokenTransaction::find()->where(['user_id' => $this->user->id])->andWhere([
			'>=',
			'date',
			date('Y-m-d H:i:s'),
		])->sum('quantity');
		$token_sold              = $token_sold ? $token_sold : 0;
		$available_token         = SellTokenForm::getAvailableToken();
		$total_tokens            = $this->user->accounts->total_tokens;
		$model                   = new SellTokenForm();
		$model_token             = new TokenMiningForm();
		$model_trading           = new TradingMiningForm();
		$model_trading->scenario = 'trading';
		$model_token->scenario   = 'mining';
		$searchModel             = new TokenTransactionSearch();
		$dataProvider            = $searchModel->search(Yii::$app->request->queryParams);
		$trading                 = $this->user->accounts->trading_account;
		$current_token           = StartSetting::find()->orderBy('id DESC')->one();
		$current_start           = StartSetting::find()->where([
			'<',
			'ABS(token_price - 0.1)',
			'0.001',
		])->orderBy('id DESC')->one();
		$current_splits          = StartSetting::find()->where([
			'>=',
			'web_start',
			$current_start->web_start,
		])->all();
		$date_array              = [];
		$price_array             = [];
		foreach($current_splits as $current_split) {
			$date_array[]  = date('d', strtotime($current_split->web_start));
			$price_array[] = $current_split->token_price;
		}
		return $this->render('exchange', [
			'token'           => $token,
			'coin'            => $coin,
			'available_token' => $available_token,
			'model'           => $model,
			'searchModel'     => $searchModel,
			'dataProvider'    => $dataProvider,
			'model_token'     => $model_token,
			'model_trading'   => $model_trading,
			'total_tokens'    => $total_tokens,
			'trading'         => $trading,
			'date_array'      => $date_array,
			'price_array'     => $price_array,
			'current_token'   => $current_token,
		]);
	}

	public function actionTokensSell() {
		$model = new SellTokenForm();
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			if($model->sellTokens()) {
				return $this->redirect(['site/exchange']);
			}
		}
		return $this->render('tokens_sell', ['model' => $model]);
	}

	public function actionTokenMining() {
		echo 'close';
		die;
		$model           = new TokenMiningForm();
		$model->scenario = 'mining';
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			if($model->tokenMining()) {
				return $this->redirect(['site/coin-mining']);
			}
		}
		return $this->render('token-mining', ['model' => $model]);
	}

	public function actionTradingMining() {
		$model           = new TradingMiningForm();
		$model->scenario = 'trading';
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			if($model->tradingMining()) {
				return $this->redirect(['site/coin-mining']);
			}
		}
		return $this->render('trading-mining', ['model' => $model]);
	}

	public function actionCoinMining() {
		$searchModel  = new CoinMiningSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$model_buy    = new BuyCoinForm();
		$model_sell   = new SellCoinFrom();
		return $this->render('coin-mining', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
			'model_buy'    => $model_buy,
			'model_sell'   => $model_sell,
		]);
	}

	/**
	 * Login action.
	 *
	 * @return string
	 */
	public function actionLogin() {
		if(!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = new LoginForm();
		if($model->load(Yii::$app->request->post()) && $model->login()) {
			parent::init();
			if(!$this->user->isBlocked) {
				Yii::$app->session->setFlash("success", "Welcome back, " . $this->user->username);
			}
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionReset() {
		if(!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = new ResetForm();
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		if($model->load(Yii::$app->request->post())) {
			$users = User::findOne([
				'email'    => $model->email,
				'username' => $model->username,
			]);
			Yii::$app->mailer->compose('reset', ['key' => $users->reset_key])->setFrom('contact.marketcoins@gmail.com')->setTo($model->email)->setSubject('Reset password link')->send();
			return $this->goBack();
		}
		return $this->render('reset', ['model' => $model]);
	}

	public function actionResetKey($key) {
		if(!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$users = User::findOne(['reset_key' => $key]);
		if($users) {
			Yii::$app->user->login($users);
			$users->updateAttributes(['reset_key' => null]);
			return $this->redirect(['user/change-password']);
		}
		return $this->render('reset-key');
	}

	/**
	 * Logout action.
	 *
	 * @return string
	 */
	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	/**
	 * Displays contact page.
	 *
	 * @return string
	 */
	public function actionContact() {
		$model = new ContactForm();
		if($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
			Yii::$app->session->setFlash('contactFormSubmitted');
			return $this->refresh();
		}
		return $this->render('contact', [
			'model' => $model,
		]);
	}

	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout() {
		return $this->render('about');
	}

	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionSignUp($key = null, $ref = null) {
		/* @var \app\models\User $user */
		$model   = new SignUpForm();
		$sponsor = null;
		$get     = Yii::$app->request->get();
		if(isset($get['ref'])) {
			$sponsor = User::findOne([
				'username' => $ref,
				//				'role'     => User::ROLE_MEMBER,
			]);
		}
		if($key != null) {
			$model->position = $key;
		}
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {

views/site/coin-mining.php
<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 3/25/2017
 * Time: 4:52 PM
 */
use miloschuman\highcharts\Highcharts;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\grid\GridView;

?>
<?php
echo \miloschuman\highcharts\Highcharts::widget([
	'options' => '{
      "title": { "text": "Marketcoins price" },
      "xAxis": {
         "categories": ["1", "2", "3","4","5","6",7,8,9,10,11,12,13,14,15,16,17,18]
      },
      "yAxis": {
         "title": { "text": "Price" }
      },
      "series": [
         { "type":"area","name": "Day price", "data": [0.1, 0.11, 0.12, 0.13, 0.14, 0.15,0.16,0.17,0.188,0.19,0.187,0.188,0.19,0.195,0.199,0.2,0.19,0.21] }
      ]
   }',
]);
?>
<?php
//echo Html::a('Mining coin', [''], ['class' => 'btn btn-warning']);
?>
	<div class="row">
		<div class="col-sm-6" style="background-color: darkred">
			<h2 style="font-weight: bold; text-align: center">Buy</h2>
			<?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>
			<?= $form->field($model_buy, 'quantity')->textInput(['readOnly' => true]) ?>
			<?= $form->field($model_buy, 'price')->textInput(['readOnly' => true,'value'=>0.362]) ?>
			<?= $form->field($model_buy, 'cash')->textInput(['readOnly' => true]) ?>
			<div class="col-sm-offset-3">
				<?= Html::submitButton($model_buy ? 'Buy' : 'Update', ['class' => $model_buy ? 'btn btn-success col-sm-3' : 'btn btn-primary']) ?>
			</div>
			<?php ActiveForm::end(); ?>
		</div>
		<div class="col-sm-6" style="background-color: #00aa00">
			<h2 style="font-weight: bold; text-align: center">Sell</h2>

			<?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>
			<?= $form->field($model_sell, 'quantity')->textInput(['readOnly' => true]) ?>
			<?= $form->field($model_sell, 'price')->textInput(['readOnly' => true,'value'=>0.36]) ?>
			<?= $form->field($model_sell, 'cash')->textInput(['readOnly' => true]) ?>
			<div class="col-sm-offset-3">
				<?= Html::submitButton($model_sell ? 'Sell' : 'Update', ['class' => $model_sell ? 'btn btn-success col-sm-3' : 'btn btn-primary']) ?>
			</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
<?= GridView::widget([
	'dataProvider' => $dataProvider,
	'columns'      => [
		['class' => 'yii\grid\SerialColumn'],
		'id',
		'start_date',
		'begin_return_coin',
		'quantity',
	],
]);

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/download.php
<?php
/**
 * Created by PhpStorm.
 * User: Yamon-PC
 * Date: 14-Jun-17
 * Time: 2:42 PM
 */
?>
<div class="col-sm-12">
	<h3>I.Company's strategy.</h3>
	<p> Tokens will be donated to members upon registration of the Course and will be split upon reaching the 100% mark of Spit.
		The member will receive two Tokens available as a guarantee and will be added to the Mining.
		Cryptocurrency will be Mining and redeploying to members beginning the internal transaction will take place until the IPO in May 2018.
		In the pre-IPO period we will focus strongly on Netwokmarketing to create community and complete Blookchain separately to connect with many cryptocurrency to ensure blouter flow.
		We are also operating system Ecosystem in some countries in the world and in our many partners, we hope MarketCoins will bring prosperity to all its owners.
		The company's strategy in terms of security is very safe for Tokens and coins, they can not disappear - just like BlockChain, we create a complete security database with hacker attacks and Safe to the customer along with the transaction, no one can steal your money. Coins left in the Wallet will be transferred in the System Transaction and will be tracked by us to secure your Safe Transactions Commitment. When you join our courses, you will be given Tokens. </p>
	<p> How Tokens will be used (what can I do with Tokens)?</p>
	<p><span style="font-weight: bold">1.</span> Sold Tokens on Exchange(1% per day). The money will be directed transfer 100% to your cash account</p>
	<p><span style="font-weight: bold">2.</span> Keep Tokens and Split in our SPLIT.</p>
	<p>
		<span style="font-weight: bold">3.</span> Invest in CRYPTO CURRENCY and participate in creating that same CRYPTO value with us. You can also increase the number of Tokens by introducing our Members to our course, and you will receive great Rewards from us. How to pay for my study package?
	</p>
	<p>- Our company accepts Payment for Finance Courses by BitCoin, PerfectMoney, Bankwire, ViSa, Euro amount in Cash Account when you own them.</p>
	<p>- The first time fee to active a package is 25€.</p>
	<?php echo \yii\helpers\Html::img(Yii::$app->urlManager->baseUrl . '/uploads/table 1.png', ['class' => 'download-image']) ?>

	<h3>II. Payment mechanism:</h3>
	<p>1. 10% bonus for each direct sales to unlimited sales.</p>
	<p>2. 10% binary bonus</p>
	<p>3. Matching bonus:</p>
	<p>- Bonus 10% to 30% Matching bonus when you help the system directly and indirectly generate small weekly BV sales volume, provided you join the 500BV package upwards, and have at least one direct Join the 500BV package for each leg.</p>
	<p>- Bonus will pay at 15:00 every monday with 40% bonus to trading account and 60% to cash account, max is 30,000 €. </p>
	<div class="download-example">
		<?php echo \yii\helpers\Html::img(Yii::$app->urlManager->baseUrl . '/uploads/table 2.png') ?>
	</div>
	<?php echo \yii\helpers\Html::img(Yii::$app->urlManager->baseUrl . '/uploads/table 3.png', ['class' => 'download-image']) ?>

	<h3>III. Award for Leader:</h3>
	<p>- With Sapphiare you reach the standard volume of 10.000BV small foot in the month, you receive 500 euro.
	<p>- With Ruby you reach the volume of 20.000BV small foot in the month and a direct Sapphiare foot small, You get 1.000 euro.</p>
	<p>- With Emerand you get standard 50.000BV small feet and a direct Ruby small legs, you get rewarded 2.000 euro.</p>
	<p>- With Diamond you reach the standard 100.000BV and a direct Emerand foot, you receive 5.000 euro + 1% of global sales.</p>
	<p>- With Blackdiamond you get standard 500.000BV small foot and 1 direct Diamond small feet you get rewarded 10.000 euro + 2% of global sales.</p>
	<p>- With Greendiamond you reach 1.000.000BV standard and 1 direct Blackdiamond small foot, you get rewarded 20.000 euro + 3% of global sales.</p>
	<p>* (Your title bonus will receive 100% on CashAcount on the 5th to the 10th of each month, the global sales reward, you will receive twice in the year).</p>
	<?php echo \yii\helpers\Html::img(Yii::$app->urlManager->baseUrl . '/uploads/table 4.png', ['class' => 'download-image']) ?>

</div>
<div class="col-sm-12">
	<?= \yii\bootstrap\Html::a('Download instruction file', ['/site/file'], ['class' => 'btn btn-success']) ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/exchange.php
<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 3/25/2017
 * Time: 4:52 PM
 */
use app\models\TokenTransaction;
use miloschuman\highcharts\Highcharts;
use yii\bootstrap\Html;
use yii\grid\GridView;

?>
<div class="col-sm-8">
	<?php
	echo \miloschuman\highcharts\Highcharts::widget([
		'options' => [
			"title"  => ["text" => "Tokens price"],
			"xAxis"  => [
				"categories" => $date_array,
			],
			"yAxis"  => [
				"title" => ["text" => "Price"],
			],
			"series" => [
				[
					"name" => "Day price",
					"data" => $price_array,
				],
			],
		],
	]);
	?>
</div>
<div class="col-sm-4">
	<?php
	echo Highcharts::widget([
		'options' => [
			'title'       => ['text' => 'Split indicator'],
			'plotOptions' => [
				'pie' => [
					'cursor'     => 'pointer',
					'dataLabels' => [
						'enabled' > true,
						'format' => '<b>{point.name}</b>: {point.percentage:.1f} %',
					],
				],
			],
			'tooltip'     => [
				'pointFormat' => '{series.name}: <b>{point.percentage:.1f}%</b>',
			],
			'series'      => [
				[ // new opening bracket
					'type' => 'pie',
					'name' => 'Split',
					'data' => [
						[
							'Split',
							$current_token->split_percent,
						],
						[
							'Left',
							100 - $current_token->split_percent,
						],
					],
				]
				// new closing bracket
			],
		],
	]);
	?>
</div>
<div class="panel panel-info">
	<div class="panel-heading">Current Tokens</div>
	<div class="panel-body font-bonus">
		<div class="col-sm-6">
			<span style="font-weight: bold">Current tokens price: </span><?= $current_token->token_price ?></div>
		<div class="col-sm-6">
			<span style="font-weight: bold">Current marketcoins price: </span><?= $current_token->coin_price ?></div>
		<div class="col-sm-6"><span style="font-weight: bold">Your tokens: </span><?= $token ?></div>
		<div class="col-sm-6"><span style="font-weight: bold">Your split tokens: </span><?= $token ?></div>
		<div class="col-sm-6"><span style="font-weight: bold">Your total tokens: </span><?= $total_tokens * 2 ?></div>
		<div class="col-sm-6"><span style="font-weight: bold">Your trading accounts: </span><?= $trading ?></div>
		<div class="col-sm-6"><span style="font-weight: bold">Your marketcoins: </span><?= $coin ?></div>
		<div class="col-sm-6">
			<span style="font-weight: bold">Your available selling tokens: </span><?= $available_token ?>
		</div>

	</div>
</div>
<?php
echo $this->render('tokens_sell', ['model' => $model]);
?>
<?php echo $this->render('token-mining', ['model' => $model_token]) ?>
<?php echo $this->render('trading-mining', ['model' => $model_trading]) ?>
<?= GridView::widget([
	'dataProvider' => $dataProvider,
	//        'filterModel' => $searchModel,
	'columns'      => [
		['class' => 'yii\grid\SerialColumn'],
		'id',
		[
			'attribute' => 'type',
			'value'     => function (TokenTransaction $data) {
				return $data::TYPE[$data->type];
			},
		],
		'date',
		'quantity',
		// 'price',
		'money',
		[
			'attribute' => 'status',
			'value'     => function (TokenTransaction $data) {
				return $data::STATUS[$data->status];
			},
		],
	],
]); ?>

views/site/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;

/* @var $user app\models\User */
$this->title = 'Futurecoin';
?>

<h3 class="page-title">
	Dashboard
	<small>reports & statistics</small>
</h3>
<!-- END PAGE HEADER-->
<!-- BEGIN DASHBOARD STATS -->
<!-- END DASHBOARD STATS -->
<div class="clearfix">
</div>

views/site/login.php
<?php
use app\assets\LoginAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

Yii::$app->layout = false;
LoginAsset::register($this);
?>
<?php $this->beginPage() ?>
<?php
$this->title                   = 'Login';
$this->params['breadcrumbs'][] = $this->title; ?>
	<!DOCTYPE html>
	<html lang="en">
	<meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
	</head>
	<!-- END HEAD -->

	<body class=" login">
	<?php $this->beginBody() ?>
	<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
	<div class="menu-toggler sidebar-toggler">
	</div>
	<!-- END SIDEBAR TOGGLER BUTTON -->
	<!-- BEGIN LOGO -->
	<div class="logo">
		<a href="#">
			<?php echo Html::img(Url::base() . '/logo.png', [
				'alt'   => 'futurecoin',
				'width' => '150px',
			]) ?>
		</a>
	</div>
	<!-- END LOGO -->
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGIN FORM -->
		<?php $form = ActiveForm::begin([
			'id' => 'login-form',
			//		'enableAjaxValidation'   => true,
			//		'enableClientValidation' => false,
			//		'validateOnBlur'         => false,
			//		'validateOnType'         => false,
			//		'validateOnChange'       => false,
		]) ?>
		<h3 class="form-title">Sign In</h3>
		<div class="form-group">
			<?= $form->field($model, 'username', ['labelOptions' => ['class' => 'control-label visible-ie8 visible-ie9']])->textInput([
				'autofocus'   => 'autofocus',
				'class'       => 'form-control form-control-solid placeholder-no-fix',
				'placeholder' => 'Username',
			]) ?>
		</div>
		<div class="form-group">
			<?= $form->field($model, 'password', ['labelOptions' => ['class' => 'control-label visible-ie8 visible-ie9']])->passwordInput([
				'class'       => 'form-control form-control-solid placeholder-no-fix',
				'placeholder' => 'Password',
			]) ?>
		</div>

		<div class="form-actions">
			<?= Html::submitButton('Login', [
				'class'    => 'btn green uppercase',
				'tabindex' => '3',
			]) ?>
			<a href="<?= Url::to(['site/reset']) ?>" id="forget-password" class="forget-password">Forgot Password?</a>
		</div>
		<?php ActiveForm::end(); ?>

		<!-- END FORGOT PASSWORD FORM -->
		<!-- BEGIN REGISTRATION FORM -->
		<!-- END REGISTRATION FORM -->
	</div>
	<div class="copyright">
		2016 © futurecoin Dashboard.
	</div>
	<?php $this->endBody() ?>
	</body>

	</html>
<?php $this->endPage() ?>

views/site/reset-key.php
<?php
/**
 * Created by PhpStorm.
 * User: Yamon-PC
 * Date: 10-Aug-17
 * Time: 10:57 AM
 */
Yii::$app->layout = false;